English:
  Graphics: null
  Settings: null
  graphics_button: Graphics
  home:
    add_task_button: Add
    add_task_hover: Add a new task
  home_button: Home
  settings_button: Settings
German:
  Graphics: null
  Settings: null
  graphics_button: Grafik
  home:
    add_task_button: "Hinzuf\xC3\xBCgen"
    add_task_hover: "Neue Aufgabe hinzuf\xC3\xBCgen"
  settings_button: Einstellungen
  thome_button: Startseite
Polish:
  Graphics: null
  Settings: null
  graphics_button: Grafika
  home:
    add_task_button: Dodaj
    add_task_hover: Dodaj nowe zadanie
  home_button: "Strona g\xC5\u201A\xC3\xB3wna"
  settings_button: Ustawienia
language: English
logo_path: src/GraphicalUI/images/logo.png
