language: English
logo_path: "images/logo.png"


##########################################################


English:

  home_button: "Home"
  graphics_button: "Graphics"
  settings_button: "Settings"

  
  home:
    add_task_hover: "Add a new task"
    add_task_button: "Add"
  
  Graphics:

  Settings:

##########################################################


Polish:
  
  home_button: "Strona główna"
  graphics_button: "Grafika"
  settings_button: "Ustawienia"
  
  
  home:
    add_task_hover: "Dodaj nowe zadanie"
    add_task_button: "Dodaj"
  
  Graphics:

  Settings:


##########################################################

German:
  
  thome_button: "Startseite"
  graphics_button: "Grafik"
  settings_button: "Einstellungen"
  
  
  home:
    add_task_hover: "Neue Aufgabe hinzufügen"
    add_task_button: "Hinzufügen"
  
  Graphics:

  Settings:
